AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/test_helper.rb
    - spec/rails_helper.rb
    - db/seeds.rb
    - config/*/*
    - config/*
    - bin/*
    - Gemfile
    - Rakefile
