# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dccdea4c9a5f2be0c533ef0618fc7fbc4498f19102a749cc27da9b6c15df333c7b2cb8fd98a30e83a50b484534e706ca6354921fb06ffb129f77e78ab0346a77

test:
  secret_key_base: 9fa49e2c7280d48e5bf9b00c3f78a16bf5289c72cb65a8e5d3c8eed1263cfece434895b98450cb446f5e530c583169ac15a26cde531b95710f490d4cc165b10c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
